[[ntl]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58ee3bf5eb07fa935fe9ef4a2806e05c14822639"
libc = "glibc"
os = "linux"

    [[ntl.download]]
    sha256 = "640a841081ac02079bd36695afa3aefca2e2ada325bdf39beff961921417fb84"
    url = "https://github.com/JuliaBinaryWrappers/ntl_jll.jl/releases/download/ntl-v11.5.1+0/ntl.v11.5.1.i686-linux-gnu-cxx03.tar.gz"
[[ntl]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "242c57d75b6c090b61728b95eb8bd217ce10faff"
libc = "glibc"
os = "linux"

    [[ntl.download]]
    sha256 = "8f41c0ba4ce4e0dfac6014e0e18352b241571d02794f35136b9c22cb56271c7c"
    url = "https://github.com/JuliaBinaryWrappers/ntl_jll.jl/releases/download/ntl-v11.5.1+0/ntl.v11.5.1.i686-linux-gnu-cxx11.tar.gz"
[[ntl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "effcf7c1792bf3db5eb3407e604cecca7ab26e40"
libc = "glibc"
os = "linux"

    [[ntl.download]]
    sha256 = "428a3ddd28c8e51592e15d6fc2ef1916bca55366b545d6268e33df8bf432b702"
    url = "https://github.com/JuliaBinaryWrappers/ntl_jll.jl/releases/download/ntl-v11.5.1+0/ntl.v11.5.1.x86_64-linux-gnu-cxx03.tar.gz"
[[ntl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a5cc25dc20516bfc353738fb2c25f1f8fa4627db"
libc = "glibc"
os = "linux"

    [[ntl.download]]
    sha256 = "649a66e1e543548c8b213f2d58bd99074bafad718fc3b7320f8e91929876fe75"
    url = "https://github.com/JuliaBinaryWrappers/ntl_jll.jl/releases/download/ntl-v11.5.1+0/ntl.v11.5.1.x86_64-linux-gnu-cxx11.tar.gz"
[[ntl]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b9d3776576d6416625249651e93e046846a7c1fb"
libc = "musl"
os = "linux"

    [[ntl.download]]
    sha256 = "785b7dbc85d93c468dcebff69e831c9fe35a55a20ab3178bce9f3617b15c7c93"
    url = "https://github.com/JuliaBinaryWrappers/ntl_jll.jl/releases/download/ntl-v11.5.1+0/ntl.v11.5.1.x86_64-linux-musl-cxx03.tar.gz"
[[ntl]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d707888f1288c6003695c7bd0b8e47b76b2ac2ab"
libc = "musl"
os = "linux"

    [[ntl.download]]
    sha256 = "79eb47f0c190c7a5fa5b039f50357c390978b66729e3da9517a8e670ce55aba2"
    url = "https://github.com/JuliaBinaryWrappers/ntl_jll.jl/releases/download/ntl-v11.5.1+0/ntl.v11.5.1.x86_64-linux-musl-cxx11.tar.gz"
